apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: nodejs-mongo-namespace
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/data/mongo
