apiVersion: v1
kind: Service
metadata:
  name: moodle-service
  namespace: moodle-namespace
  labels:
    app: moodle
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: moodle
