apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: nodejs-namespace
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /data/mongo-pv
