apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  namespace: nodejs-namespace
  labels:
    app: nodeapp
spec:
  type: LoadBalancer
  selector:
    app: nodeapp
  ports:
  - protocol: TCP
    port: 30000
    targetPort: 3000
