apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  namespace: nodejs-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - name: nodeapp
        image: aleksunir/k8s-node-app:latest
        env:
        - name: MONGO_URL
          value: "mongodb://mongodb:27017/db"
        ports:
        - containerPort: 3000
