apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  namespace: nodejs-mongo-namespace
  labels:
    app: nodejs
spec:
  replicas: 2 # Se requiere al menos dos réplicas
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: aleksunir/act02_nodejs
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URL
          value: "mongodb://mongodb-service:27017"
